In [1]:
import torch

In [17]:
x = torch.tensor([[1,2],[3,4]])

In [18]:
x.shape

torch.Size([2, 2])

In [19]:
x1 = torch.repeat_interleave(x ,2)
x1

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [20]:
x2 = torch.repeat_interleave(x , 2, 0)
x2

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])

In [21]:
x3 = torch.repeat_interleave(x , 2, 1)
x3

tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])

In [25]:
x3.shape[1]

4

In [23]:
x3.reshape(-1)

tensor([1, 1, 2, 2, 3, 3, 4, 4])

In [24]:
x3

tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])

In [55]:
mask = torch.arange((2), dtype=torch.float32)

In [59]:
mask

tensor([0., 1.])

In [56]:
mask.shape

torch.Size([2])

In [57]:
mask1 = mask[None,:]

In [60]:
mask1

tensor([[0., 1.]])

In [58]:
mask1.shape

torch.Size([1, 2])

In [18]:
valid_Len = 4

In [ ]:
mask = torch.arange((maxlen), dtype=torch.float32)[None, :] < valid_len[:, None]

In [122]:
def sequence_mask(X, valid_len, value=0):
    """Mask irrelevant entries in sequences.

    Defined in :numref:`sec_seq2seq_decoder`"""
    maxlen = X.size(1)  # (batch_size, max_length, feature_dim)
    mask = torch.arange((maxlen), dtype=torch.float32, device=X.device)[None, :] < valid_len[:, None]
    print(mask)
    X[~mask] = value
    return X


X为[3,4,3],maxlen为4，valid_len为[2,2,2]

torch.arrange 生成 [0,1,2,3]

torch.arrage[None,:]就是[[0,1,2,3]] shape是[1,4]

valid[:,None]就变成[3,1]


In [123]:
X = torch.rand([3,4,3])
Y = torch.tensor([1,2,3])
print(X)
sequence_mask(X, Y)

tensor([[[0.9584, 0.5395, 0.1835],
         [0.4342, 0.4944, 0.4845],
         [0.9108, 0.3239, 0.9424],
         [0.9311, 0.4065, 0.3140]],

        [[0.3266, 0.5624, 0.3409],
         [0.9463, 0.4756, 0.7618],
         [0.2632, 0.4876, 0.2388],
         [0.4592, 0.4987, 0.8974]],

        [[0.7358, 0.0374, 0.9678],
         [0.4887, 0.5133, 0.2005],
         [0.2771, 0.6327, 0.3620],
         [0.4185, 0.5058, 0.3583]]])
tensor([[ True, False, False, False],
        [ True,  True, False, False],
        [ True,  True,  True, False]])


tensor([[[0.9584, 0.5395, 0.1835],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.3266, 0.5624, 0.3409],
         [0.9463, 0.4756, 0.7618],
         [0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000]],

        [[0.7358, 0.0374, 0.9678],
         [0.4887, 0.5133, 0.2005],
         [0.2771, 0.6327, 0.3620],
         [0.0000, 0.0000, 0.0000]]])

In [136]:
X = torch.arange(12,dtype=torch.float32).reshape(2,2,3)

In [137]:
y = X.softmax(dim = -1)

In [138]:
print(y)

tensor([[[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]],

        [[0.0900, 0.2447, 0.6652],
         [0.0900, 0.2447, 0.6652]]])


In [139]:
a = torch.ones(2,3)

In [140]:
a

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [141]:
a = a.reshape(-1)

In [142]:
a

tensor([1., 1., 1., 1., 1., 1.])